### PR TITLE
Add id3 tags to mp3 file

### LINKED ISSUE #11: Feature request: ID3 tags
Would be really nice if some of the video information could be written as ID3 tags, author, title, publish date, description, thumbnail.

I tried to setup my own dev environment but failed :disappointed: is easiest using vagrant? should be `cd ansible; vagrant up` more or less? https://gist.github.com/wader/3f1fd3d3da203f43b6e9

### PR DESCRIPTION
**Pull request by wader**
Fixes #11

### CODE REVIEW

**Comment by wader** [comment]
@jcalazan is this something you would like to add?

**Comment by jcalazan** [comment]
Hey Mattias,

Sorry for the delay, this is great!  Thanks!

**Comment by wader** [comment]
Nice, no problem! when will it be available at http://www.youtubeadl.com?

**Comment by jcalazan** [comment]
I actually already pushed, but I'm currently fixing my rabbitmq server, be back up soon hopefully.

**Comment by wader** [comment]
:+1:

**Comment by jcalazan** [comment]
Back up! Your change is there, looks good!

**Pull request merged**
